/// Returns localized topic data based on locale code.
/// Each topic has 20-30 subtopics.
Map<String, List<String>> getLocalizedTopicData(String localeCode) {
  switch (localeCode) {
    case 'tr':
      return _topicDataTr;
    case 'de':
      return _topicDataDe;
    case 'fr':
      return _topicDataFr;
    case 'es':
      return _topicDataEs;
    case 'ar':
      return _topicDataAr;
    default:
      return _topicDataEn;
  }
}

// ─── ENGLISH ─────────────────────────────────────────────
final Map<String, List<String>> _topicDataEn = {
  'Math': [
    'Algebra',
    'Geometry',
    'Calculus',
    'Trigonometry',
    'Statistics',
    'Numbers',
    'Functions',
    'Equations',
    'Polynomials',
    'Logarithm',
    'Complex Numbers',
    'Probability',
    'Limits',
    'Integrals',
    'Derivatives',
    'Matrices',
    'Vectors',
    'Set Theory',
    'Logic',
    'Sequences',
    'Solid Geometry',
    'Analytic Geometry',
    'Permutation',
    'Combination',
    'Binomial Expansion',
    'Modular Arithmetic',
    'Commercial Math',
    'Financial Math',
    'Discrete Math',
    'Number Theory'
  ],
  'Science': [
    'Physics: Mechanics',
    'Physics: Electricity',
    'Physics: Optics',
    'Physics: Thermodynamics',
    'Chemistry: Organic',
    'Chemistry: Atoms',
    'Chemistry: Periodic Table',
    'Chemistry: Bonds',
    'Biology: Cells',
    'Biology: Genetics',
    'Biology: Human Systems',
    'Biology: Ecology',
    'Astronomy: Solar System',
    'Astronomy: Stars',
    'Earth Science: Geology',
    'Earth Science: Atmosphere',
    'Physics: Nuclear',
    'Physics: Relativity',
    'Chemistry: Acids & Bases',
    'Chemistry: Solutions',
    'Biology: Evolution',
    'Biology: Plant Biology',
    'Biology: Microbiology',
    'Environmental Science',
    'Physics: Waves',
    'Physics: Magnetism',
    'Chemistry: Kinetics',
    'Chemistry: Electrochemistry',
    'Biology: Biotechnology',
    'Biology: Biochemistry'
  ],
  'History': [
    'Ancient Civilizations',
    'Middle Ages',
    'Renaissance',
    'Industrial Revolution',
    'World War I',
    'World War II',
    'Cold War',
    'Modern Era',
    'Ottoman Empire',
    'Seljuk Empire',
    'Byzantine Era',
    'Roman Empire',
    'French Revolution',
    'American Revolution',
    'Age of Discovery',
    'Prehistory',
    'Ancient Egypt',
    'Ancient Greece',
    'Middle Eastern History',
    'European History',
    'Central Asian History',
    'African History',
    'Post-War Reconstruction',
    'Contemporary History',
    'Era of Reformations',
    'Crusades',
    'Napoleonic Wars',
    'Colonialism',
    'Ancient Mesopotamia',
    'Ancient China'
  ],
  'Literature': [
    'Poetry Analysis',
    'Novel Genres',
    'Drama & Theatre',
    'Short Story',
    'Epic Traditions',
    'Classical Literature',
    'Romanticism',
    'Realism',
    'Modernism',
    'Turkish Literature',
    'English Literature',
    'Russian Literature',
    'French Literature',
    'Literary Devices',
    'Authors and Works',
    'Period Pieces',
    'Post-Modernism',
    'Renaissance Literature',
    'Victorian Era',
    'Greek Mythology',
    'Critical Theory',
    'Linguistics',
    'Comparative Literature',
    'Creative Writing',
    'Folk Literature',
    'Divan Literature',
    'Contemporary Poetry',
    'World Classics',
    'Gothic Fiction',
    'Symbolism'
  ],
  'Technology': [
    'Computer Science Basics',
    'Artificial Intelligence',
    'Software Development',
    'Cybersecurity',
    'Networking Protocols',
    'Database Management',
    'Cloud Computing',
    'Mobile Apps',
    'Hardware Engineering',
    'Robotics',
    'Internet of Things',
    'Blockchain',
    'Web Design',
    'Data Science',
    'Machine Learning',
    'Ethical Hacking',
    'DevOps',
    'Game Development',
    'Operating Systems',
    'Embedded Systems',
    'Quantum Computing',
    'Digital Marketing Tech',
    'Big Data',
    'Virtual Reality',
    'Augmented Reality',
    'E-commerce Tech',
    'Systems Analysis',
    'UI/UX Design',
    'Automation',
    'API Development'
  ],
  'Art': [
    'Classical Painting',
    'Sculpture Techniques',
    'Architectural History',
    'Music Theory',
    'Modern Photography',
    'Film and Cinema',
    'Art History Survey',
    'Digital Art',
    'Graphic Design',
    'Modern Art',
    'Baroque Art',
    'Impressionism',
    'Surrealism',
    'Pop Art',
    'Abstract Art',
    'Renaissance Art',
    'Medieval Architecture',
    'Gothic Art',
    'Cinema History',
    'Documentary Film',
    'Electronic Music',
    'Jazz History',
    'Dance & Choreography',
    'Industrial Design',
    'Fashion Design',
    'Interior Design',
    'Ceramics',
    'Calligraphy',
    'Illustration',
    'Printmaking'
  ],
  'General': [
    'Philosophy: Logic',
    'Philosophy: Ethics',
    'Psychology Basics',
    'Sociology',
    'Human Geography',
    'Economics 101',
    'Current Global Events',
    'Microeconomics',
    'Macroeconomics',
    'Political Science',
    'International Relations',
    'Social Media Culture',
    'Nutrition & Health',
    'Personal Development',
    'Critical Thinking',
    'Mythology',
    'Religious Studies',
    'Anthropology',
    'Environment & Sustainability',
    'Legal Systems',
    'Human Rights',
    'Mass Media',
    'Urban Studies',
    'Demographics',
    'Business Management',
    'Entrepreneurship',
    'Marketing Basics',
    'Public Speaking',
    'Cultural Studies',
    'Civics'
  ]
};

// ─── TURKISH ─────────────────────────────────────────────
final Map<String, List<String>> _topicDataTr = {
  'Matematik': [
    'Cebir',
    'Geometri',
    'Kalkülüs',
    'Trigonometri',
    'İstatistik',
    'Sayılar',
    'Fonksiyonlar',
    'Denklemler',
    'Polinomlar',
    'Logaritma',
    'Karmaşık Sayılar',
    'Olasılık',
    'Limitler',
    'İntegral',
    'Türev',
    'Matrisler',
    'Vektörler',
    'Küme Teorisi',
    'Mantık',
    'Diziler',
    'Uzay Geometri',
    'Analitik Geometri',
    'Permütasyon',
    'Kombinasyon',
    'Binom Açılımı',
    'Modüler Aritmetik',
    'Ticari Matematik',
    'Finansal Matematik',
    'Ayrık Matematik',
    'Sayılar Teorisi'
  ],
  'Fen Bilimleri': [
    'Fizik: Mekanik',
    'Fizik: Elektrik',
    'Fizik: Optik',
    'Fizik: Termodinamik',
    'Kimya: Organik',
    'Kimya: Atomlar',
    'Kimya: Periyodik Tablo',
    'Kimya: Bağlar',
    'Biyoloji: Hücreler',
    'Biyoloji: Genetik',
    'Biyoloji: İnsan Sistemleri',
    'Biyoloji: Ekoloji',
    'Astronomi: Güneş Sistemi',
    'Astronomi: Yıldızlar',
    'Yer Bilimi: Jeoloji',
    'Yer Bilimi: Atmosfer',
    'Fizik: Nükleer',
    'Fizik: Görelilik',
    'Kimya: Asitler ve Bazlar',
    'Kimya: Çözeltiler',
    'Biyoloji: Evrim',
    'Biyoloji: Bitki Biyolojisi',
    'Biyoloji: Mikrobiyoloji',
    'Çevre Bilimi',
    'Fizik: Dalgalar',
    'Fizik: Manyetizma',
    'Kimya: Kinetik',
    'Kimya: Elektrokimya',
    'Biyoloji: Biyoteknoloji',
    'Biyoloji: Biyokimya'
  ],
  'Tarih': [
    'Antik Uygarlıklar',
    'Orta Çağ',
    'Rönesans',
    'Sanayi Devrimi',
    'I. Dünya Savaşı',
    'II. Dünya Savaşı',
    'Soğuk Savaş',
    'Modern Dönem',
    'Osmanlı İmparatorluğu',
    'Selçuklu Devleti',
    'Bizans Dönemi',
    'Roma İmparatorluğu',
    'Fransız Devrimi',
    'Amerikan Devrimi',
    'Keşifler Çağı',
    'Tarih Öncesi',
    'Antik Mısır',
    'Antik Yunan',
    'Orta Doğu Tarihi',
    'Avrupa Tarihi',
    'Orta Asya Tarihi',
    'Afrika Tarihi',
    'Savaş Sonrası Dönem',
    'Çağdaş Tarih',
    'Islahatlar Dönemi',
    'Haçlı Seferleri',
    'Napolyon Savaşları',
    'Sömürgecilik',
    'Antik Mezopotamya',
    'Antik Çin'
  ],
  'Edebiyat': [
    'Şiir Analizi',
    'Roman Türleri',
    'Tiyatro',
    'Hikaye',
    'Destan',
    'Klasik Edebiyat',
    'Romantizm',
    'Realizm',
    'Modernizm',
    'Türk Edebiyatı',
    'İngiliz Edebiyatı',
    'Rus Edebiyatı',
    'Fransız Edebiyatı',
    'Edebi Sanatlar',
    'Yazarlar ve Eserleri',
    'Dönem Eserleri',
    'Post-Modernizm',
    'Rönesans Edebiyatı',
    'Viktorya Dönemi',
    'Yunan Mitolojisi',
    'Eleştiri Kuramı',
    'Dilbilim',
    'Karşılaştırmalı Edebiyat',
    'Yaratıcı Yazarlık',
    'Halk Edebiyatı',
    'Divan Edebiyatı',
    'Çağdaş Şiir',
    'Dünya Klasikleri',
    'Gotik Kurgu',
    'Sembolizm'
  ],
  'Teknoloji': [
    'Bilgisayar Bilimi',
    'Yapay Zeka',
    'Yazılım Geliştirme',
    'Siber Güvenlik',
    'Ağ Protokolleri',
    'Veritabanı Yönetimi',
    'Bulut Bilişim',
    'Mobil Uygulamalar',
    'Donanım Mühendisliği',
    'Robotik',
    'Nesnelerin İnterneti',
    'Blok Zinciri',
    'Web Tasarım',
    'Veri Bilimi',
    'Makine Öğrenmesi',
    'Etik Hackleme',
    'DevOps',
    'Oyun Geliştirme',
    'İşletim Sistemleri',
    'Gömülü Sistemler',
    'Kuantum Bilişim',
    'Dijital Pazarlama',
    'Büyük Veri',
    'Sanal Gerçeklik',
    'Artırılmış Gerçeklik',
    'E-Ticaret Teknolojisi',
    'Sistem Analizi',
    'UI/UX Tasarım',
    'Otomasyon',
    'API Geliştirme'
  ],
  'Sanat': [
    'Klasik Resim',
    'Heykel Teknikleri',
    'Mimari Tarih',
    'Müzik Teorisi',
    'Modern Fotoğrafçılık',
    'Sinema',
    'Sanat Tarihi',
    'Dijital Sanat',
    'Grafik Tasarım',
    'Modern Sanat',
    'Barok Sanat',
    'Empresyonizm',
    'Sürrealizm',
    'Pop Art',
    'Soyut Sanat',
    'Rönesans Sanatı',
    'Ortaçağ Mimarisi',
    'Gotik Sanat',
    'Sinema Tarihi',
    'Belgesel Film',
    'Elektronik Müzik',
    'Caz Tarihi',
    'Dans ve Koreografi',
    'Endüstriyel Tasarım',
    'Moda Tasarım',
    'İç Mimarlık',
    'Seramik',
    'Hat Sanatı',
    'İllüstrasyon',
    'Baskı Sanatı'
  ],
  'Genel Kültür': [
    'Felsefe: Mantık',
    'Felsefe: Etik',
    'Temel Psikoloji',
    'Sosyoloji',
    'Beşeri Coğrafya',
    'Ekonomi 101',
    'Güncel Olaylar',
    'Mikroekonomi',
    'Makroekonomi',
    'Siyaset Bilimi',
    'Uluslararası İlişkiler',
    'Sosyal Medya Kültürü',
    'Beslenme ve Sağlık',
    'Kişisel Gelişim',
    'Eleştirel Düşünce',
    'Mitoloji',
    'Din Bilimi',
    'Antropoloji',
    'Çevre ve Sürdürülebilirlik',
    'Hukuk Sistemleri',
    'İnsan Hakları',
    'Kitle İletişimi',
    'Şehircilik',
    'Demografi',
    'İşletme Yönetimi',
    'Girişimcilik',
    'Pazarlama',
    'Topluluk Önünde Konuşma',
    'Kültürel Çalışmalar',
    'Vatandaşlık'
  ]
};

// ─── GERMAN ──────────────────────────────────────────────
final Map<String, List<String>> _topicDataDe = {
  'Mathematik': [
    'Algebra',
    'Geometrie',
    'Analysis',
    'Trigonometrie',
    'Statistik',
    'Zahlen',
    'Funktionen',
    'Gleichungen',
    'Polynome',
    'Logarithmus',
    'Komplexe Zahlen',
    'Wahrscheinlichkeit',
    'Grenzwerte',
    'Integrale',
    'Ableitungen',
    'Matrizen',
    'Vektoren',
    'Mengenlehre',
    'Logik',
    'Folgen',
    'Raumgeometrie',
    'Analytische Geometrie',
    'Permutation',
    'Kombination',
    'Binomische Reihe',
    'Modulare Arithmetik',
    'Wirtschaftsmathe',
    'Finanzmathematik',
    'Diskrete Mathe',
    'Zahlentheorie'
  ],
  'Naturwissenschaften': [
    'Physik: Mechanik',
    'Physik: Elektrizität',
    'Physik: Optik',
    'Physik: Thermodynamik',
    'Chemie: Organisch',
    'Chemie: Atome',
    'Chemie: Periodensystem',
    'Chemie: Bindungen',
    'Biologie: Zellen',
    'Biologie: Genetik',
    'Biologie: Menschliche Systeme',
    'Biologie: Ökologie',
    'Astronomie: Sonnensystem',
    'Astronomie: Sterne',
    'Geowissenschaft: Geologie',
    'Geowissenschaft: Atmosphäre',
    'Physik: Kernphysik',
    'Physik: Relativität',
    'Chemie: Säuren & Basen',
    'Chemie: Lösungen',
    'Biologie: Evolution',
    'Biologie: Pflanzenbiologie',
    'Biologie: Mikrobiologie',
    'Umweltwissenschaft',
    'Physik: Wellen',
    'Physik: Magnetismus',
    'Chemie: Kinetik',
    'Chemie: Elektrochemie',
    'Biologie: Biotechnologie',
    'Biologie: Biochemie'
  ],
  'Geschichte': [
    'Antike Zivilisationen',
    'Mittelalter',
    'Renaissance',
    'Industrielle Revolution',
    'Erster Weltkrieg',
    'Zweiter Weltkrieg',
    'Kalter Krieg',
    'Moderne Ära',
    'Osmanisches Reich',
    'Seldschuken',
    'Byzantinische Ära',
    'Römisches Reich',
    'Französische Revolution',
    'Amerikanische Revolution',
    'Zeitalter der Entdeckungen',
    'Vorgeschichte',
    'Altes Ägypten',
    'Antikes Griechenland',
    'Nahost-Geschichte',
    'Europäische Geschichte',
    'Zentralasiatische Geschichte',
    'Afrikanische Geschichte',
    'Nachkriegszeit',
    'Zeitgeschichte',
    'Reformationszeitalter',
    'Kreuzzüge',
    'Napoleonische Kriege',
    'Kolonialismus',
    'Altes Mesopotamien',
    'Altes China'
  ],
  'Literatur': [
    'Gedichtanalyse',
    'Romangattungen',
    'Drama & Theater',
    'Kurzgeschichte',
    'Epos',
    'Klassische Literatur',
    'Romantik',
    'Realismus',
    'Moderne',
    'Türkische Literatur',
    'Englische Literatur',
    'Russische Literatur',
    'Französische Literatur',
    'Stilmittel',
    'Autoren und Werke',
    'Epochenwerke',
    'Postmoderne',
    'Renaissance-Literatur',
    'Viktorianische Ära',
    'Griechische Mythologie',
    'Literaturkritik',
    'Linguistik',
    'Vergleichende Literatur',
    'Kreatives Schreiben',
    'Volksliteratur',
    'Divan-Literatur',
    'Zeitgenössische Poesie',
    'Weltklassiker',
    'Gotische Fiktion',
    'Symbolismus'
  ],
  'Technologie': [
    'Informatik Grundlagen',
    'Künstliche Intelligenz',
    'Softwareentwicklung',
    'Cybersicherheit',
    'Netzwerkprotokolle',
    'Datenbankverwaltung',
    'Cloud Computing',
    'Mobile Apps',
    'Hardwaretechnik',
    'Robotik',
    'Internet der Dinge',
    'Blockchain',
    'Webdesign',
    'Datenwissenschaft',
    'Maschinelles Lernen',
    'Ethisches Hacken',
    'DevOps',
    'Spieleentwicklung',
    'Betriebssysteme',
    'Eingebettete Systeme',
    'Quantencomputing',
    'Digitales Marketing',
    'Big Data',
    'Virtuelle Realität',
    'Erweiterte Realität',
    'E-Commerce-Technik',
    'Systemanalyse',
    'UI/UX Design',
    'Automatisierung',
    'API-Entwicklung'
  ],
  'Kunst': [
    'Klassische Malerei',
    'Bildhauertechniken',
    'Architekturgeschichte',
    'Musiktheorie',
    'Moderne Fotografie',
    'Film und Kino',
    'Kunstgeschichte',
    'Digitale Kunst',
    'Grafikdesign',
    'Moderne Kunst',
    'Barockkunst',
    'Impressionismus',
    'Surrealismus',
    'Pop Art',
    'Abstrakte Kunst',
    'Renaissance-Kunst',
    'Mittelalterliche Architektur',
    'Gotische Kunst',
    'Kinogeschichte',
    'Dokumentarfilm',
    'Elektronische Musik',
    'Jazz-Geschichte',
    'Tanz & Choreografie',
    'Industriedesign',
    'Modedesign',
    'Innenarchitektur',
    'Keramik',
    'Kalligrafie',
    'Illustration',
    'Druckgrafik'
  ],
  'Allgemeinwissen': [
    'Philosophie: Logik',
    'Philosophie: Ethik',
    'Grundlagen Psychologie',
    'Soziologie',
    'Humangeographie',
    'Wirtschaft 101',
    'Aktuelle Weltereignisse',
    'Mikroökonomie',
    'Makroökonomie',
    'Politikwissenschaft',
    'Internationale Beziehungen',
    'Social-Media-Kultur',
    'Ernährung & Gesundheit',
    'Persönlichkeitsentwicklung',
    'Kritisches Denken',
    'Mythologie',
    'Religionswissenschaft',
    'Anthropologie',
    'Umwelt & Nachhaltigkeit',
    'Rechtssysteme',
    'Menschenrechte',
    'Massenmedien',
    'Urbanistik',
    'Demografie',
    'Betriebswirtschaft',
    'Unternehmertum',
    'Marketing-Grundlagen',
    'Öffentliches Reden',
    'Kulturwissenschaft',
    'Staatsbürgerkunde'
  ]
};

// ─── FRENCH ──────────────────────────────────────────────
final Map<String, List<String>> _topicDataFr = {
  'Mathématiques': [
    'Algèbre',
    'Géométrie',
    'Calcul',
    'Trigonométrie',
    'Statistiques',
    'Nombres',
    'Fonctions',
    'Équations',
    'Polynômes',
    'Logarithme',
    'Nombres complexes',
    'Probabilités',
    'Limites',
    'Intégrales',
    'Dérivées',
    'Matrices',
    'Vecteurs',
    'Théorie des ensembles',
    'Logique',
    'Suites',
    'Géométrie dans l\'espace',
    'Géométrie analytique',
    'Permutation',
    'Combinaison',
    'Développement binomial',
    'Arithmétique modulaire',
    'Maths commerciales',
    'Maths financières',
    'Maths discrètes',
    'Théorie des nombres'
  ],
  'Sciences': [
    'Physique: Mécanique',
    'Physique: Électricité',
    'Physique: Optique',
    'Physique: Thermodynamique',
    'Chimie: Organique',
    'Chimie: Atomes',
    'Chimie: Tableau périodique',
    'Chimie: Liaisons',
    'Biologie: Cellules',
    'Biologie: Génétique',
    'Biologie: Systèmes humains',
    'Biologie: Écologie',
    'Astronomie: Système solaire',
    'Astronomie: Étoiles',
    'Sciences de la Terre: Géologie',
    'Sciences de la Terre: Atmosphère',
    'Physique: Nucléaire',
    'Physique: Relativité',
    'Chimie: Acides & Bases',
    'Chimie: Solutions',
    'Biologie: Évolution',
    'Biologie: Botanique',
    'Biologie: Microbiologie',
    'Sciences de l\'environnement',
    'Physique: Ondes',
    'Physique: Magnétisme',
    'Chimie: Cinétique',
    'Chimie: Électrochimie',
    'Biologie: Biotechnologie',
    'Biologie: Biochimie'
  ],
  'Histoire': [
    'Civilisations antiques',
    'Moyen Âge',
    'Renaissance',
    'Révolution industrielle',
    'Première Guerre mondiale',
    'Seconde Guerre mondiale',
    'Guerre froide',
    'Ère moderne',
    'Empire ottoman',
    'Empire seldjoukide',
    'Ère byzantine',
    'Empire romain',
    'Révolution française',
    'Révolution américaine',
    'Âge des découvertes',
    'Préhistoire',
    'Égypte antique',
    'Grèce antique',
    'Histoire du Moyen-Orient',
    'Histoire européenne',
    'Histoire de l\'Asie centrale',
    'Histoire africaine',
    'Reconstruction d\'après-guerre',
    'Histoire contemporaine',
    'Époque des réformes',
    'Croisades',
    'Guerres napoléoniennes',
    'Colonialisme',
    'Mésopotamie antique',
    'Chine antique'
  ],
  'Littérature': [
    'Analyse de poésie',
    'Genres de roman',
    'Théâtre',
    'Nouvelle',
    'Traditions épiques',
    'Littérature classique',
    'Romantisme',
    'Réalisme',
    'Modernisme',
    'Littérature turque',
    'Littérature anglaise',
    'Littérature russe',
    'Littérature française',
    'Figures de style',
    'Auteurs et œuvres',
    'Œuvres par période',
    'Post-modernisme',
    'Littérature de la Renaissance',
    'Époque victorienne',
    'Mythologie grecque',
    'Théorie critique',
    'Linguistique',
    'Littérature comparée',
    'Écriture créative',
    'Littérature populaire',
    'Littérature de Divan',
    'Poésie contemporaine',
    'Classiques mondiaux',
    'Fiction gothique',
    'Symbolisme'
  ],
  'Technologie': [
    'Informatique de base',
    'Intelligence artificielle',
    'Développement logiciel',
    'Cybersécurité',
    'Protocoles réseau',
    'Gestion de bases de données',
    'Cloud computing',
    'Applications mobiles',
    'Ingénierie matérielle',
    'Robotique',
    'Internet des objets',
    'Blockchain',
    'Conception web',
    'Science des données',
    'Apprentissage automatique',
    'Piratage éthique',
    'DevOps',
    'Développement de jeux',
    'Systèmes d\'exploitation',
    'Systèmes embarqués',
    'Informatique quantique',
    'Marketing numérique',
    'Big Data',
    'Réalité virtuelle',
    'Réalité augmentée',
    'Technologies e-commerce',
    'Analyse de systèmes',
    'Design UI/UX',
    'Automatisation',
    'Développement d\'API'
  ],
  'Art': [
    'Peinture classique',
    'Techniques de sculpture',
    'Histoire de l\'architecture',
    'Théorie musicale',
    'Photographie moderne',
    'Cinéma',
    'Histoire de l\'art',
    'Art numérique',
    'Design graphique',
    'Art moderne',
    'Art baroque',
    'Impressionnisme',
    'Surréalisme',
    'Pop Art',
    'Art abstrait',
    'Art de la Renaissance',
    'Architecture médiévale',
    'Art gothique',
    'Histoire du cinéma',
    'Film documentaire',
    'Musique électronique',
    'Histoire du jazz',
    'Danse & Chorégraphie',
    'Design industriel',
    'Design de mode',
    'Architecture d\'intérieur',
    'Céramique',
    'Calligraphie',
    'Illustration',
    'Gravure'
  ],
  'Culture générale': [
    'Philosophie: Logique',
    'Philosophie: Éthique',
    'Bases de psychologie',
    'Sociologie',
    'Géographie humaine',
    'Économie 101',
    'Actualités mondiales',
    'Microéconomie',
    'Macroéconomie',
    'Sciences politiques',
    'Relations internationales',
    'Culture des réseaux sociaux',
    'Nutrition & Santé',
    'Développement personnel',
    'Pensée critique',
    'Mythologie',
    'Études religieuses',
    'Anthropologie',
    'Environnement & Durabilité',
    'Systèmes juridiques',
    'Droits de l\'homme',
    'Médias de masse',
    'Urbanisme',
    'Démographie',
    'Gestion d\'entreprise',
    'Entrepreneuriat',
    'Bases du marketing',
    'Prise de parole en public',
    'Études culturelles',
    'Éducation civique'
  ]
};

// ─── SPANISH ─────────────────────────────────────────────
final Map<String, List<String>> _topicDataEs = {
  'Matemáticas': [
    'Álgebra',
    'Geometría',
    'Cálculo',
    'Trigonometría',
    'Estadística',
    'Números',
    'Funciones',
    'Ecuaciones',
    'Polinomios',
    'Logaritmo',
    'Números complejos',
    'Probabilidad',
    'Límites',
    'Integrales',
    'Derivadas',
    'Matrices',
    'Vectores',
    'Teoría de conjuntos',
    'Lógica',
    'Sucesiones',
    'Geometría del espacio',
    'Geometría analítica',
    'Permutación',
    'Combinación',
    'Expansión binomial',
    'Aritmética modular',
    'Matemáticas comerciales',
    'Matemáticas financieras',
    'Matemáticas discretas',
    'Teoría de números'
  ],
  'Ciencias': [
    'Física: Mecánica',
    'Física: Electricidad',
    'Física: Óptica',
    'Física: Termodinámica',
    'Química: Orgánica',
    'Química: Átomos',
    'Química: Tabla periódica',
    'Química: Enlaces',
    'Biología: Células',
    'Biología: Genética',
    'Biología: Sistemas humanos',
    'Biología: Ecología',
    'Astronomía: Sistema solar',
    'Astronomía: Estrellas',
    'Ciencias de la Tierra: Geología',
    'Ciencias de la Tierra: Atmósfera',
    'Física: Nuclear',
    'Física: Relatividad',
    'Química: Ácidos y Bases',
    'Química: Soluciones',
    'Biología: Evolución',
    'Biología: Botánica',
    'Biología: Microbiología',
    'Ciencia ambiental',
    'Física: Ondas',
    'Física: Magnetismo',
    'Química: Cinética',
    'Química: Electroquímica',
    'Biología: Biotecnología',
    'Biología: Bioquímica'
  ],
  'Historia': [
    'Civilizaciones antiguas',
    'Edad Media',
    'Renacimiento',
    'Revolución Industrial',
    'Primera Guerra Mundial',
    'Segunda Guerra Mundial',
    'Guerra Fría',
    'Era moderna',
    'Imperio otomano',
    'Imperio selyúcida',
    'Era bizantina',
    'Imperio romano',
    'Revolución Francesa',
    'Revolución Americana',
    'Era de los Descubrimientos',
    'Prehistoria',
    'Antiguo Egipto',
    'Antigua Grecia',
    'Historia de Medio Oriente',
    'Historia europea',
    'Historia de Asia Central',
    'Historia africana',
    'Reconstrucción posguerra',
    'Historia contemporánea',
    'Era de las Reformas',
    'Cruzadas',
    'Guerras napoleónicas',
    'Colonialismo',
    'Antigua Mesopotamia',
    'Antigua China'
  ],
  'Literatura': [
    'Análisis de poesía',
    'Géneros de novela',
    'Drama y Teatro',
    'Cuento',
    'Tradiciones épicas',
    'Literatura clásica',
    'Romanticismo',
    'Realismo',
    'Modernismo',
    'Literatura turca',
    'Literatura inglesa',
    'Literatura rusa',
    'Literatura francesa',
    'Figuras literarias',
    'Autores y obras',
    'Obras por período',
    'Post-modernismo',
    'Literatura renacentista',
    'Era victoriana',
    'Mitología griega',
    'Teoría crítica',
    'Lingüística',
    'Literatura comparada',
    'Escritura creativa',
    'Literatura popular',
    'Literatura de Diván',
    'Poesía contemporánea',
    'Clásicos mundiales',
    'Ficción gótica',
    'Simbolismo'
  ],
  'Tecnología': [
    'Informática básica',
    'Inteligencia artificial',
    'Desarrollo de software',
    'Ciberseguridad',
    'Protocolos de red',
    'Gestión de bases de datos',
    'Computación en la nube',
    'Aplicaciones móviles',
    'Ingeniería de hardware',
    'Robótica',
    'Internet de las cosas',
    'Blockchain',
    'Diseño web',
    'Ciencia de datos',
    'Aprendizaje automático',
    'Hacking ético',
    'DevOps',
    'Desarrollo de juegos',
    'Sistemas operativos',
    'Sistemas embebidos',
    'Computación cuántica',
    'Marketing digital',
    'Big Data',
    'Realidad virtual',
    'Realidad aumentada',
    'Tecnología e-commerce',
    'Análisis de sistemas',
    'Diseño UI/UX',
    'Automatización',
    'Desarrollo de API'
  ],
  'Arte': [
    'Pintura clásica',
    'Técnicas de escultura',
    'Historia de la arquitectura',
    'Teoría musical',
    'Fotografía moderna',
    'Cine',
    'Historia del arte',
    'Arte digital',
    'Diseño gráfico',
    'Arte moderno',
    'Arte barroco',
    'Impresionismo',
    'Surrealismo',
    'Pop Art',
    'Arte abstracto',
    'Arte renacentista',
    'Arquitectura medieval',
    'Arte gótico',
    'Historia del cine',
    'Cine documental',
    'Música electrónica',
    'Historia del jazz',
    'Danza y Coreografía',
    'Diseño industrial',
    'Diseño de moda',
    'Diseño de interiores',
    'Cerámica',
    'Caligrafía',
    'Ilustración',
    'Grabado'
  ],
  'Cultura general': [
    'Filosofía: Lógica',
    'Filosofía: Ética',
    'Bases de psicología',
    'Sociología',
    'Geografía humana',
    'Economía 101',
    'Eventos globales actuales',
    'Microeconomía',
    'Macroeconomía',
    'Ciencia política',
    'Relaciones internacionales',
    'Cultura de redes sociales',
    'Nutrición y Salud',
    'Desarrollo personal',
    'Pensamiento crítico',
    'Mitología',
    'Estudios religiosos',
    'Antropología',
    'Medio ambiente y Sostenibilidad',
    'Sistemas legales',
    'Derechos humanos',
    'Medios masivos',
    'Urbanismo',
    'Demografía',
    'Administración de empresas',
    'Emprendimiento',
    'Fundamentos de marketing',
    'Oratoria',
    'Estudios culturales',
    'Educación cívica'
  ]
};

// ─── ARABIC ──────────────────────────────────────────────
final Map<String, List<String>> _topicDataAr = {
  'الرياضيات': [
    'الجبر',
    'الهندسة',
    'التفاضل والتكامل',
    'حساب المثلثات',
    'الإحصاء',
    'الأعداد',
    'الدوال',
    'المعادلات',
    'كثيرات الحدود',
    'اللوغاريتمات',
    'الأعداد المركبة',
    'الاحتمالات',
    'النهايات',
    'التكاملات',
    'المشتقات',
    'المصفوفات',
    'المتجهات',
    'نظرية المجموعات',
    'المنطق',
    'المتتاليات',
    'الهندسة الفراغية',
    'الهندسة التحليلية',
    'التباديل',
    'التوافيق',
    'نظرية ذات الحدين',
    'الحساب المعياري',
    'الرياضيات التجارية',
    'الرياضيات المالية',
    'الرياضيات المتقطعة',
    'نظرية الأعداد'
  ],
  'العلوم': [
    'فيزياء: الميكانيكا',
    'فيزياء: الكهرباء',
    'فيزياء: البصريات',
    'فيزياء: الديناميكا الحرارية',
    'كيمياء: عضوية',
    'كيمياء: الذرات',
    'كيمياء: الجدول الدوري',
    'كيمياء: الروابط',
    'أحياء: الخلايا',
    'أحياء: الوراثة',
    'أحياء: أجهزة الجسم',
    'أحياء: علم البيئة',
    'فلك: النظام الشمسي',
    'فلك: النجوم',
    'علوم الأرض: الجيولوجيا',
    'علوم الأرض: الغلاف الجوي',
    'فيزياء: النووية',
    'فيزياء: النسبية',
    'كيمياء: الأحماض والقواعد',
    'كيمياء: المحاليل',
    'أحياء: التطور',
    'أحياء: النبات',
    'أحياء: الأحياء الدقيقة',
    'علوم البيئة',
    'فيزياء: الأمواج',
    'فيزياء: المغناطيسية',
    'كيمياء: الحركية',
    'كيمياء: الكهروكيمياء',
    'أحياء: التكنولوجيا الحيوية',
    'أحياء: الكيمياء الحيوية'
  ],
  'التاريخ': [
    'الحضارات القديمة',
    'العصور الوسطى',
    'عصر النهضة',
    'الثورة الصناعية',
    'الحرب العالمية الأولى',
    'الحرب العالمية الثانية',
    'الحرب الباردة',
    'العصر الحديث',
    'الإمبراطورية العثمانية',
    'الدولة السلجوقية',
    'العصر البيزنطي',
    'الإمبراطورية الرومانية',
    'الثورة الفرنسية',
    'الثورة الأمريكية',
    'عصر الاكتشافات',
    'ما قبل التاريخ',
    'مصر القديمة',
    'اليونان القديمة',
    'تاريخ الشرق الأوسط',
    'التاريخ الأوروبي',
    'تاريخ آسيا الوسطى',
    'التاريخ الأفريقي',
    'إعادة البناء بعد الحرب',
    'التاريخ المعاصر',
    'عصر الإصلاحات',
    'الحروب الصليبية',
    'حروب نابليون',
    'الاستعمار',
    'بلاد الرافدين القديمة',
    'الصين القديمة'
  ],
  'الأدب': [
    'تحليل الشعر',
    'أنواع الرواية',
    'الدراما والمسرح',
    'القصة القصيرة',
    'الملاحم',
    'الأدب الكلاسيكي',
    'الرومانسية',
    'الواقعية',
    'الحداثة',
    'الأدب التركي',
    'الأدب الإنجليزي',
    'الأدب الروسي',
    'الأدب الفرنسي',
    'الأساليب الأدبية',
    'المؤلفون وأعمالهم',
    'أعمال حسب الحقبة',
    'ما بعد الحداثة',
    'أدب عصر النهضة',
    'العصر الفيكتوري',
    'الأساطير اليونانية',
    'النظرية النقدية',
    'علم اللغة',
    'الأدب المقارن',
    'الكتابة الإبداعية',
    'الأدب الشعبي',
    'أدب الديوان',
    'الشعر المعاصر',
    'الكلاسيكيات العالمية',
    'الخيال القوطي',
    'الرمزية'
  ],
  'التكنولوجيا': [
    'أساسيات علوم الحاسوب',
    'الذكاء الاصطناعي',
    'تطوير البرمجيات',
    'الأمن السيبراني',
    'بروتوكولات الشبكات',
    'إدارة قواعد البيانات',
    'الحوسبة السحابية',
    'تطبيقات الجوال',
    'هندسة العتاد',
    'الروبوتات',
    'إنترنت الأشياء',
    'سلسلة الكتل',
    'تصميم الويب',
    'علم البيانات',
    'التعلم الآلي',
    'القرصنة الأخلاقية',
    'DevOps',
    'تطوير الألعاب',
    'أنظمة التشغيل',
    'الأنظمة المدمجة',
    'الحوسبة الكمومية',
    'التسويق الرقمي',
    'البيانات الضخمة',
    'الواقع الافتراضي',
    'الواقع المعزز',
    'تقنيات التجارة الإلكترونية',
    'تحليل النظم',
    'تصميم UI/UX',
    'الأتمتة',
    'تطوير API'
  ],
  'الفن': [
    'الرسم الكلاسيكي',
    'تقنيات النحت',
    'تاريخ العمارة',
    'نظرية الموسيقى',
    'التصوير الحديث',
    'السينما',
    'تاريخ الفن',
    'الفن الرقمي',
    'التصميم الجرافيكي',
    'الفن الحديث',
    'فن الباروك',
    'الانطباعية',
    'السريالية',
    'فن البوب',
    'الفن التجريدي',
    'فن عصر النهضة',
    'العمارة في العصور الوسطى',
    'الفن القوطي',
    'تاريخ السينما',
    'الأفلام الوثائقية',
    'الموسيقى الإلكترونية',
    'تاريخ الجاز',
    'الرقص والتصميم',
    'التصميم الصناعي',
    'تصميم الأزياء',
    'التصميم الداخلي',
    'الخزف',
    'الخط',
    'الرسم التوضيحي',
    'الطباعة الفنية'
  ],
  'ثقافة عامة': [
    'فلسفة: المنطق',
    'فلسفة: الأخلاق',
    'أساسيات علم النفس',
    'علم الاجتماع',
    'الجغرافيا البشرية',
    'اقتصاد 101',
    'الأحداث العالمية',
    'الاقتصاد الجزئي',
    'الاقتصاد الكلي',
    'العلوم السياسية',
    'العلاقات الدولية',
    'ثقافة وسائل التواصل',
    'التغذية والصحة',
    'التنمية الذاتية',
    'التفكير النقدي',
    'الأساطير',
    'الدراسات الدينية',
    'علم الإنسان',
    'البيئة والاستدامة',
    'الأنظمة القانونية',
    'حقوق الإنسان',
    'وسائل الإعلام',
    'التحضر',
    'الديموغرافيا',
    'إدارة الأعمال',
    'ريادة الأعمال',
    'أساسيات التسويق',
    'الخطابة',
    'الدراسات الثقافية',
    'التربية المدنية'
  ]
};
